---
  name: Auto-deployment of Schema Documentation
  permissions:
      contents: read
  on:
      push:
          branches: [main]

  jobs:
      build-docs:
          runs-on: ubuntu-latest
          steps:
              - name: Checkout
                uses: actions/checkout@main
                with:
                    fetch-depth: 0

              - name: Set up Python 3.
                uses: actions/setup-python@main
                with:
                  python-version: 3.13

              - name: Install uv
                uses: astral-sh/setup-uv@v6

              - name: Build documentation.
                run: |
                    uv sync
                    make gendoc-gh
